//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashBook.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.EventGalaries = new HashSet<EventGalary>();
            this.EventGroups = new HashSet<EventGroup>();
            this.EventUsers = new HashSet<EventUser>();
        }
    
        public int EventId { get; set; }
        public int EntityTypeId { get; set; }
        public int EntityId { get; set; }
        public int OccationId { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Message { get; set; }
        public long DateTime { get; set; }
        public long CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<long> LastUpdatedOn { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
    
        public virtual LookUpValue LookUpValue { get; set; }
        public virtual LookUpValue LookUpValue1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventGalary> EventGalaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventGroup> EventGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventUser> EventUsers { get; set; }
    }
}
