//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashBook.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventGalary
    {
        public int EventGalaryId { get; set; }
        public int EventId { get; set; }
        public int TypeId { get; set; }
        public string Url { get; set; }
        public long CreatedOn { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual LookUpValue LookUpValue { get; set; }
        public virtual User User { get; set; }
    }
}
