//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashBook.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.MatchQuestions = new HashSet<MatchQuestion>();
            this.MatchUserAnswers = new HashSet<MatchUserAnswer>();
            this.MatchUserScores = new HashSet<MatchUserScore>();
            this.MatchUserTeams = new HashSet<MatchUserTeam>();
        }
    
        public int MatchId { get; set; }
        public int TournamentId { get; set; }
        public int HomeTeamId { get; set; }
        public int OpponentTeamId { get; set; }
        public int StatusId { get; set; }
        public int GroundId { get; set; }
        public int Number { get; set; }
        public long StartsOn { get; set; }
        public string Result { get; set; }
    
        public virtual Ground Ground { get; set; }
        public virtual LookUpValue LookUpValue { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual Tournament Tournament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchQuestion> MatchQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchUserAnswer> MatchUserAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchUserScore> MatchUserScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchUserTeam> MatchUserTeams { get; set; }
    }
}
