//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashBook.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchUserTeam
    {
        public int MatchUserTeamId { get; set; }
        public int MatchId { get; set; }
        public int UserId { get; set; }
        public int TeamId { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
    }
}
