//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashBook.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatchQuestion()
        {
            this.MatchUserAnswers = new HashSet<MatchUserAnswer>();
        }
    
        public int MatchQuestionId { get; set; }
        public int MatchId { get; set; }
        public int QuestionId { get; set; }
        public int PredictionCategoryId { get; set; }
        public Nullable<int> Answer { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual PredictionCategory PredictionCategory { get; set; }
        public virtual Question Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchUserAnswer> MatchUserAnswers { get; set; }
    }
}
