//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashBook.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poll()
        {
            this.EntityPolls = new HashSet<EntityPoll>();
            this.Options = new HashSet<Option>();
            this.UserVotes = new HashSet<UserVote>();
        }
    
        public int PollId { get; set; }
        public int SelectionTypeId { get; set; }
        public int OptionTypeId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> VisibilityId { get; set; }
        public string Text { get; set; }
        public string Image { get; set; }
        public bool IsActive { get; set; }
        public bool IsVotingCompleted { get; set; }
        public long CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<long> LastUpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityPoll> EntityPolls { get; set; }
        public virtual LookUpValue LookUpValue { get; set; }
        public virtual LookUpValue LookUpValue1 { get; set; }
        public virtual LookUpValue LookUpValue2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Option> Options { get; set; }
        public virtual PollCategory PollCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserVote> UserVotes { get; set; }
    }
}
