//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashBook.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostLike
    {
        public int PostLikeId { get; set; }
        public int PostId { get; set; }
        public int LikedBy { get; set; }
        public long LikedOn { get; set; }
        public bool Status { get; set; }
        public Nullable<long> LastUpdatedOn { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
