//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashBook.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostComment
    {
        public int PostCommentId { get; set; }
        public int PostId { get; set; }
        public int TypeId { get; set; }
        public string Url { get; set; }
        public string Text { get; set; }
        public long CommentedOn { get; set; }
        public int CommentedBy { get; set; }
    
        public virtual LookUpValue LookUpValue { get; set; }
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
