//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashBook.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostShare
    {
        public int PostShareId { get; set; }
        public int PostId { get; set; }
        public int EntityTypeId { get; set; }
        public int EntityId { get; set; }
        public long SharedOn { get; set; }
        public int SharedBy { get; set; }
    
        public virtual LookUpValue LookUpValue { get; set; }
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
