//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashBook.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredictionCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PredictionCategory()
        {
            this.MatchQuestions = new HashSet<MatchQuestion>();
            this.TournamentQuestions = new HashSet<TournamentQuestion>();
        }
    
        public int PredictionCategoryId { get; set; }
        public string Name { get; set; }
        public int CategoryTypeId { get; set; }
        public int WinPoints { get; set; }
        public int LossPoints { get; set; }
        public int BonusTimes { get; set; }
    
        public virtual LookUpValue LookUpValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchQuestion> MatchQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentQuestion> TournamentQuestions { get; set; }
    }
}
