//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashBook.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.MatchQuestions = new HashSet<MatchQuestion>();
            this.QuestionRules = new HashSet<QuestionRule>();
            this.TournamentQuestions = new HashSet<TournamentQuestion>();
        }
    
        public int QuestionId { get; set; }
        public string Text { get; set; }
        public string Image { get; set; }
        public int SelectionTypeId { get; set; }
        public int OptionsTypeId { get; set; }
        public Nullable<int> LookupParentId { get; set; }
        public Nullable<int> LookupDisplayTypeId { get; set; }
        public Nullable<bool> IsForMatch { get; set; }
    
        public virtual LookUpValue LookUpValue { get; set; }
        public virtual LookUpValue LookUpValue1 { get; set; }
        public virtual LookUpValue LookUpValue2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchQuestion> MatchQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionRule> QuestionRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentQuestion> TournamentQuestions { get; set; }
    }
}
