//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashBook.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentUserAnswer
    {
        public int TournamentUserAnswerId { get; set; }
        public int TournamentQuestionId { get; set; }
        public int UserId { get; set; }
        public int Answer { get; set; }
    
        public virtual TournamentQuestion TournamentQuestion { get; set; }
        public virtual User User { get; set; }
    }
}
