//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashBook.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserContact
    {
        public int UserContactId { get; set; }
        public int UserId { get; set; }
        public int ContactId { get; set; }
        public int ContactStatusId { get; set; }
        public long RequestedOn { get; set; }
        public Nullable<long> AcceptedOn { get; set; }
    
        public virtual LookUpValue LookUpValue { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
