//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashBook.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOccation
    {
        public int UserOccationId { get; set; }
        public int UserId { get; set; }
        public int OccationId { get; set; }
        public long Date { get; set; }
        public long CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<long> LastUpdatedOn { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
    
        public virtual LookUpValue LookUpValue { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
